version: "3.9"
services:
  prist:
    image: nehcy/prist
    container_name: prist 
    build: 
      context: .
      args:
        NB_DIR: work
        NB_USER: wald
    command: ["python", "main.py"]
    environment:
      - TG_TOKEN=${TELEGRAM_TOKEN}
#    volumes:
#      - ./src:/home/${NB_USER}/work
    init: true
    restart: always
    stdin_open: true    
    network_mode: bridge
    tty: true
