version: "3.9"
services:
  redmine-bot:
    image: nehcy/botus
    container_name: redmine-bot 
    command: ["python", "main.py"]
    environment:
      - TG_TOKEN=${TELEGRAM_TOKEN}
      - READMINE_KEY=${READMINE_KEY}
    volumes:
      - ./src:/home/${NB_USER}/src
    init: true
    restart: always
    stdin_open: true    
    network_mode: bridge
    tty: true
