version: "3.9"
services:
  agitko:
    image: nehcy/botus
    container_name: AGItko 
    command: ["python", "main.py"]
    environment:
      - TG_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./src:/home/${NB_USER}/work
    network_mode: bridge
    restart: always
